services:
  web:
    build: .
    container_name: project3-web
    expose:
      - "8000"
    # ⬇️ 요거 추가! (호스트 코드 → 컨테이너 /app 으로 마운트)
    volumes:
      - .:/app
      - static_volume:/app/static      # ← web이 collectstatic 한 걸 여기 넣어줌
    env_file:
      - .env
    depends_on:
      - db              # 👈 db 먼저 뜨게
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: project3-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: project3-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static     # 👈 web이 만든 static을 nginx도 본다
    depends_on:
      - web

volumes:
  static_volume: {}    # ← 이 줄이 없어서 에러났던 거야
  postgres_data: {}   # 👈 Postgres 데이터가 여기 남음
