# Generated by Django 5.2.6 on 2025-10-20 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="메시지에 첨부된 이미지 파일",
                        null=True,
                        upload_to="chat_images/",
                    ),
                ),
                ("is_user", models.BooleanField(default=True)),
                (
                    "character_emotion",
                    models.CharField(
                        blank=True,
                        help_text="AI 캐릭터의 감정 상태",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(blank=True, help_text="활동 날짜", null=True),
                ),
                (
                    "activity_time",
                    models.TimeField(blank=True, help_text="활동 시간", null=True),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, help_text="장소", max_length=255, null=True
                    ),
                ),
                (
                    "companion",
                    models.CharField(
                        blank=True, help_text="동행인", max_length=255, null=True
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True, help_text="활동 관련 메모 또는 대화 내용", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_onboarding_complete",
                    models.BooleanField(
                        default=False, help_text="사용자 초기 설정(온보딩) 완료 여부"
                    ),
                ),
                (
                    "affinity_score",
                    models.IntegerField(
                        default=0, help_text="AI '아이'와의 호감도 점수"
                    ),
                ),
                (
                    "memory",
                    models.JSONField(
                        default=dict, help_text="사용자에 대한 기억 저장소"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "주간"),
                            ("monthly", "월간"),
                            ("yearly", "연간"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start_date", models.DateField(help_text="통계 기간의 시작일")),
                (
                    "place",
                    models.CharField(db_index=True, help_text="장소", max_length=255),
                ),
                (
                    "companion",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="동행인",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0, help_text="해당 기간 동안의 방문 횟수"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("user", "period_type", "period_start_date", "place", "companion")
                },
            },
        ),
        migrations.CreateModel(
            name="UserAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fact_type",
                    models.CharField(
                        blank=True,
                        help_text="속성의 종류 (예: '성격', 'MBTI', '생일')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True,
                        help_text="속성 내용 (예: '털털함', 'INFP', '1995-10-31')",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "fact_type", "content")},
            },
        ),
        migrations.CreateModel(
            name="UserRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="동일 인물 구분을 위한 고유 시리얼 코드",
                        unique=True,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        help_text="관계 유형 (예: 가족, 친구, 직장 동료)",
                        max_length=100,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="관계 내 포지션 (예: 오빠, 친한 친구, 상사)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="상대방 이름", max_length=100)),
                (
                    "disambiguator",
                    models.CharField(
                        blank=True,
                        help_text="동명이인 구분을 위한 식별자 (예: '개발팀', '친구')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "traits",
                    models.TextField(
                        blank=True, help_text="상대방 성격 또는 특징", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "serial_code")},
            },
        ),
        migrations.CreateModel(
            name="UserSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="일과 날짜")),
                ("content", models.TextField(blank=True, help_text="하루 일과 내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
