# Generated by Django 5.2.6 on 2025-10-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userschedule",
            name="schedule_time",
            field=models.TimeField(blank=True, help_text="일과 시간", null=True),
        ),
    ]
