# Generated by Django 5.2.6 on 2025-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0003_pendingproactivemessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userschedule",
            options={"ordering": ["date", "schedule_time"]},
        ),
        migrations.AlterUniqueTogether(
            name="userschedule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chatbot_name",
            field=models.CharField(
                default="아이", help_text="사용자가 지정한 챗봇 이름", max_length=100
            ),
        ),
    ]
