# Generated by Django 5.2.7 on 2025-10-28 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_alter_userschedule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userschedule',
            options={'ordering': ['date', '-schedule_time']},
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='퀴즈 장르', max_length=100)),
                ('num_questions', models.IntegerField(help_text='총 문제 수')),
                ('score', models.IntegerField(help_text='획득 점수')),
                ('date_completed', models.DateTimeField(auto_now_add=True, help_text='퀴즈 완료 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
    ]
