# Generated by Django 5.2.7 on 2025-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_alter_userschedule_options_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='genre',
            field=models.CharField(choices=[('all', '랜덤'), ('korean_history', '한국사'), ('world_history', '세계사'), ('science', '과학'), ('literature', '문학'), ('general', '상식')], help_text='퀴즈 장르', max_length=100),
        ),
    ]
