# Generated by Django 5.2.6 on 2025-10-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0006_alter_quizresult_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chatbot_style",
            field=models.CharField(
                default="친근한",
                help_text="챗봇의 대화 스타일 (예: 친근한, 전문적인, 유머러스한)",
                max_length=100,
            ),
        ),
    ]
