# Generated by Django 5.2.6 on 2025-10-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0007_userprofile_chatbot_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="chatbot_style",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="persona_preference",
            field=models.CharField(
                default="친근한", help_text="챗봇의 스타일", max_length=100
            ),
        ),
    ]
