# Generated by Django 5.2.7 on 2025-10-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0009_userfriendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='사용자 프로필 사진', null=True, upload_to='profile_pics/'),
        ),
    ]
