# Generated by Django 5.2.7 on 2025-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0010_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status_message',
            field=models.CharField(blank=True, help_text='사용자 상태 메시지', max_length=255, null=True),
        ),
    ]
