# Generated by Django 5.2.6 on 2025-10-31 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0010_friendmessage"),
        ("chatbot_app", "0010_userprofile_profile_picture"),
    ]

    operations = []
