# Generated by Django 5.2.6 on 2025-10-31 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0011_merge_20251031_1228"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True, help_text="사용자 닉네임", max_length=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="friendmessage",
            index=models.Index(
                fields=["receiver", "is_read"], name="chatbot_app_receive_aae096_idx"
            ),
        ),
    ]
