# Generated by Django 5.2.6 on 2025-10-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0011_userprofile_status_message"),
        ("chatbot_app", "0012_remove_userprofile_profile_picture_and_more"),
    ]

    operations = []
