# Generated by Django 5.2.6 on 2025-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0012_useractivity_delete_intermediatememory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_onboarding_complete",
            field=models.BooleanField(
                default=False, help_text="사용자 초기 설정(온보딩) 완료 여부"
            ),
        ),
    ]
