# Generated by Django 5.2.7 on 2025-10-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0013_userprofile_is_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_b64_data',
            field=models.TextField(blank=True, help_text='Base64 encoded image data if message includes an image', null=True),
        ),
    ]
