# Generated by Django 5.2.6 on 2025-10-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0014_chatmessage_character_emotion"),
        ("chatbot_app", "0014_userschedule"),
    ]

    operations = []
