# Generated by Django 5.2.6 on 2025-10-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0014_userschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="character_emotion",
            field=models.CharField(
                blank=True, help_text="AI 캐릭터의 감정 상태", max_length=50, null=True
            ),
        ),
    ]
