# Generated by Django 5.2.7 on 2025-11-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0014_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/cute_pig.jpg', help_text='사용자 프로필 사진', null=True, upload_to='profile_pics/'),
        ),
    ]
