# Generated by Django 5.2.6 on 2025-10-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0014_chatmessage_image_b64_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="image_b64_data",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="메시지에 첨부된 이미지 파일",
                null=True,
                upload_to="chat_images/",
            ),
        ),
    ]
